// Configuracion. API_URL vacio = modo local (cada navegador guarda lo suyo). Para cuentas reales: API_URL="api/api.php"
const API_URL="";
const GOOGLE_CLIENT_ID=""; // opcional, solo para Google real con servidor
// Idiomas, textos de la interfaz y cuenta admin
// Todos los idiomas ISO 639-1 (los nombres se generan solos en el idioma de la interfaz)
const CODES="aa ab ae af ak am an ar as av ay az ba be bg bi bm bn bo br bs ca ce ch co cr cs cu cv cy da de dv dz ee el en eo es et eu fa ff fi fj fo fr fy ga gd gl gn gu gv ha he hi ho hr ht hu hy hz ia id ie ig ii ik io is it iu ja jv ka kg ki kj kk kl km kn ko kr ks ku kv kw ky la lb lg li ln lo lt lu lv mg mh mi mk ml mn mr ms mt my na nb nd ne ng nl nn no nr nv ny oc oj om or os pa pi pl ps pt qu rm rn ro ru rw sa sc sd se sg si sk sl sm sn so sq sr ss st su sv sw ta te tg th ti tk tl tn to tr ts tt tw ty ug uk ur uz ve vi vo wa wo xh yi yo za zh zh-TW zu ceb haw hmn".split(" ");
const RTL=["ar","he","fa","ur","ps","sd","ug","yi","dv"];
const dn=(c,l)=>{try{const n=new Intl.DisplayNames([l],{type:"language"}).of(c)||c;return n.charAt(0).toUpperCase()+n.slice(1)}catch{return c}};
let LANGS={};
function buildLangs(){const o={auto:t("auto")};CODES.map(c=>[c,dn(c,ui)]).sort((a,b)=>a[1].localeCompare(b[1],ui)).forEach(([c,n])=>o[c]=n);LANGS=o}
const I={es:{prof:"Perfil",save:"Guardar cambios",saved:"Guardado",bio:"Sobre ti",oldp:"Contraseña actual",newp:"Nueva contraseña (opcional)",photo:"Foto de perfil",of:"de",used:"usadas",e_bad:"Datos incorrectos",e_exists:"Ese usuario o correo ya existe",e_banned:"Esta cuenta está bloqueada",e_auth:"Inicia sesión primero",e_pass:"La contraseña necesita al menos 6 caracteres",e_user:"Usuario: 3-20 letras, números . _ -",e_net:"Sin conexión con el servidor",e_limit:"Modo advertencia: llegaste a tu límite de traducciones. Espera a que el administrador lo quite.",notice:"Las traducciones hechas con una cuenta registrada se guardan y el administrador puede revisarlas.",auto:"Detectar idioma",all:"Todas las fuentes",nores:"Sin resultados en",find:"Buscar",login:"Iniciar sesión",logout:"Salir",sub:"Traduce cualquier idioma del mundo",text:"Texto",doc:"Documentos",img:"Fotos",aud:"Audio",voc:"Vocabulario",usr:"Cuentas",go:"Traducir",ph:"Escribe aquí…",docnote:"Formatos: txt, md, csv, srt, html, json",dl:"Descargar",rec:"Hablar y traducir",by:"Creado por",ok:"Aceptar",sw:"Crear cuenta / Entrar",user:"Usuario",email:"Correo",pass:"Contraseña",left:"gratis restantes",unl:"Ilimitado",limit:"Ya usaste tus 15 traducciones gratis. Inicia sesión para seguir.",from:"De",to:"A"},
en:{prof:"Profile",save:"Save changes",saved:"Saved",bio:"About you",oldp:"Current password",newp:"New password (optional)",photo:"Profile photo",of:"of",used:"used",e_bad:"Wrong details",e_exists:"That username or email already exists",e_banned:"This account is blocked",e_auth:"Log in first",e_pass:"The password needs at least 6 characters",e_user:"Username: 3-20 letters, numbers . _ -",e_net:"No connection to the server",e_limit:"Warning mode: you reached your translation limit. Wait for the administrator to lift it.",notice:"Translations made with a registered account are saved and can be reviewed by the administrator.",auto:"Detect language",all:"All sources",nores:"No results in",find:"Search",login:"Log in",logout:"Log out",sub:"Translate every language in the world",text:"Text",doc:"Documents",img:"Photos",aud:"Audio",voc:"Vocabulary",usr:"Accounts",go:"Translate",ph:"Type here…",docnote:"Formats: txt, md, csv, srt, html, json",dl:"Download",rec:"Speak & translate",by:"Created by",ok:"OK",sw:"Sign up / Log in",user:"Username",email:"Email",pass:"Password",left:"free left",unl:"Unlimited",limit:"You used your 15 free translations. Log in to continue.",from:"From",to:"To"},
fr:{auto:"Détecter la langue",all:"Toutes les sources",nores:"Aucun résultat dans",find:"Chercher",login:"Connexion",logout:"Sortir",sub:"Traduisez toutes les langues du monde",text:"Texte",doc:"Documents",img:"Photos",aud:"Audio",voc:"Vocabulaire",usr:"Comptes",go:"Traduire",ph:"Écrivez ici…",docnote:"Formats : txt, md, csv, srt, html, json",dl:"Télécharger",rec:"Parler et traduire",by:"Créé par",ok:"OK",sw:"Créer un compte / Connexion",user:"Utilisateur",email:"E-mail",pass:"Mot de passe",left:"gratuites restantes",unl:"Illimité",limit:"15 traductions gratuites utilisées. Connectez-vous.",from:"De",to:"Vers"},
pt:{auto:"Detectar idioma",all:"Todas as fontes",nores:"Sem resultados em",find:"Buscar",login:"Entrar",logout:"Sair",sub:"Traduza todos os idiomas do mundo",text:"Texto",doc:"Documentos",img:"Fotos",aud:"Áudio",voc:"Vocabulário",usr:"Contas",go:"Traduzir",ph:"Escreva aqui…",docnote:"Formatos: txt, md, csv, srt, html, json",dl:"Baixar",rec:"Falar e traduzir",by:"Criado por",ok:"OK",sw:"Criar conta / Entrar",user:"Usuário",email:"E-mail",pass:"Senha",left:"grátis restantes",unl:"Ilimitado",limit:"Você usou as 15 traduções grátis. Entre para continuar.",from:"De",to:"Para"}};
